<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <style media="screen">
      body{
      margin-top:10px;
      background:#eee;
  }

    </style>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
       <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
       <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>
  <body>
    <div class="container bootdey">
    <div class="row invoice row-printable">
        <div class="col-md-10">
            <!-- col-lg-12 start here -->
            <div class="panel panel-default plain" id="dash_0">
                <!-- Start .panel -->
                <div class="panel-body p30">
                    <div class="row">
                        <!-- Start .row -->
                        <div class="col-lg-6">
                            <!-- col-lg-6 start here -->
                            <div class="invoice-logo"><img width="100" src="{{ public_path().'/images/logo1.png' }}" alt="Invoice logo"></div>
                        </div>
                        <!-- col-lg-6 end here -->
                        <div class="col-lg-6 mt-2">
                            <!-- col-lg-6 start here -->
                            <div class="invoice-from d-flex justify-content-end">
                                <ul class="list-unstyled text-right">
                                    <li>Noorsaffron Ltd</li>
                                    <li>Lahore,Pakistan</li>
                                    <li>03123456789</li>
                                    <!-- <li>VAT Number EU826113958</li> -->
                                </ul>
                            </div>
                        </div>
                        <!-- col-lg-6 end here -->
                        <div class="col-lg-12">
                            <!-- col-lg-12 start here -->
                            <div class="invoice-details mt25">
                            <div class="well">
                                <div class="row">
                                    <div class="col-md-6">
                                        <ul class="list-unstyled mb0">
                                            <li><strong>Generated Date:</strong> {{ now()->format('d-m-Y') }}</li>
                                            <li><strong>Generated By:</strong> <span style="color:black">{{ Auth()->user()->name }}</span></li>
                                        </ul>
                                    </div>
                                    <div class="col-md-6 text-right">
                                        <ul class="list-unstyled mb0">
                                            <li><strong>From:</strong> {{$start_date}} </li> <!-- Replace $fromDate with your actual variable -->
                                            <li><strong>To:</strong> {{$end_date}} </li> <!-- Replace $toDate with your actual variable -->
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                            <div class="invoice-to mt25">
                                <ul class="list-unstyled">
                                    <!-- <li><strong>Invoiced To</strong></li> -->
                                   
                                </ul>
                            </div>
                            <div class="invoice-items">
                                <div class="table-responsive" style="overflow: hidden; outline: none;" tabindex="0">
                                    <table id="my-table" class="table table-bordered" style="width: 100%;">
                                        <thead>
                                            <tr>
                                               
											    <th class="per70 text-center">Order Date</th>                                              
                                                <th class="per70 text-center">Product Name</th>
                                                <th class="per5 text-center">Price</th>
												<th class="per5 text-center">Qty</th>
                                                <th class="per5 text-center">Payment Status</th>
                                                <th class="per5 text-center">Delivery Status</th>
                                                <th class="per25 text-center">Total</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php $total=0; ?>
                                            @foreach($orders as $key => $order)
                                            <?php $total += $order->price; ?>
                                            <tr>
												
                                                <td class="text-center">{{$order->created_at}}</td>
												<td class="text-center">{{$order->product_title}}</td>
                                                <td class="text-center">${{$order->price}}</td>
                                                <td class="text-center">{{$order->quantity}}</td>
                                                <td class="text-center">{{$order->payment_status}}</td>
                                                <td class="text-center">{{$order->delivery_status}}</td>
                                                <td class="text-center">${{$order->price}}</td>
												
                                            </tr>
                                            @endforeach
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th colspan="6" class="text-right">Sub Total:</th>
                                                <td class="text-center">${{$total}}</td>
                                            </tr>
                                            <tr>
                                                <th colspan="6" class="text-right">20% VAT:</th>
                                                <td class="text-center">$0</td>
                                            </tr>
                                            <tr>
                                                <th colspan="6" class="text-right">Credit:</th>
                                                <td class="text-center">$0</td>
                                            </tr>
                                            <tr>
                                                <th colspan="6" class="text-right">Total:</th>
                                                <td class="text-center">${{$total}}</td>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                            <div class="invoice-footer mt25">
                                <p class="text-center">Generated By Noorsaffron.com <a href="#" class="btn btn-default ml15"><i class="fa fa-print mr5"></i></a></p>
                            </div>
                        </div>
                        <!-- col-lg-12 end here -->
                    </div>
                    <!-- End .row -->
                </div>
            </div>
            <!-- End .panel -->
        </div>
        <!-- col-lg-12 end here -->
    </div>
    </div>

  </body>
</html>
